### ISSUE TITLE
Finish the documentation

### ISSUE THREAD

**Issue by AlbaSS18** [Arquisoft/dechat_es3b#4]
We must do the following points:

* 5. Building Block View

**Comment by yagogr98** [comment]
The introduction is actually ended, will continue with the glossary

**Comment by yagogr98** [comment]
Changed the issue, now only the final parts are left.

**Comment by yagogr98** [comment]
Edited, just 5, 6 and 7 are left

**Comment by yagogr98** [comment]
Edited. Only part 5 is pending. Must talk with the team before being done. The code structure is still changing.

**Comment by yagogr98** [comment]
Documentation is finished. Maybe some changes will happen after this

**Comment by yagogr98** [comment]
Documentation is finished. Maybe some changes will happen after this
