### ISSUE TITLE
Explore this to start to develop the app

### ISSUE THREAD

**Issue by Maarr** [Arquisoft/dechat_es3b#9]
https://webrtc.github.io/samples/src/content/datachannel/messaging/

**Comment by Maarr** [comment]
https://webrtc.github.io/samples/src/content/datachannel/basic/

**Comment by Maarr** [comment]
http://laboratoriosweb.blogspot.com/

**Comment by Maarr** [comment]
https://www.npmjs.com/package/simple-peer

**Comment by AlbaSS18** [comment]
I add web pages that can be interesting:

- https://github.com/solid/solid-apps
- https://biking.michael-simons.eu/docs/index.html

**Comment by davidrico97** [comment]
Nice ide for angular and web develop
https://stackblitz.com/
